name: Run PHP_CodeSniffer with reviewdog
description: Run PHP_CodeSniffer with reviewdog
author: hrysd

inputs:
  github_token:
    description: API TOKEN
    required: true

  level:
    description: Report level for reviewdog command
    default: error

  reporter:
    description: Reporter for reviewdog command
    default: github-pr-check

  standard:
    description: Coding standard or path to configuration file
    required: true

  target_directory:
    description: Directory to check by PHP_CodeSniffer
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - ${{ inputs.standard }}
    - ${{ inputs.target_directory }}
